/*
    This file is part of Magnum.

    Copyright © 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019,
                2020, 2021 Vladimír Vondruš <mosra@centrum.cz>
    Copyright © 2021 Pablo Escobar <mail@rvrs.in>

    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

/* Autogenerated from formatMapping.py! Do not edit! */

#ifdef _p /* PixelFormat */
_p(9, R8Unorm, UNORM)
_p(16, RG8Unorm, UNORM)
_p(23, RGB8Unorm, UNORM)
_p(37, RGBA8Unorm, UNORM)
_p(10, R8Snorm, SNORM)
_p(17, RG8Snorm, SNORM)
_p(24, RGB8Snorm, SNORM)
_p(38, RGBA8Snorm, SNORM)
_p(15, R8Srgb, SRGB)
_p(22, RG8Srgb, SRGB)
_p(29, RGB8Srgb, SRGB)
_p(43, RGBA8Srgb, SRGB)
_p(13, R8UI, UINT)
_p(20, RG8UI, UINT)
_p(27, RGB8UI, UINT)
_p(41, RGBA8UI, UINT)
_p(14, R8I, SINT)
_p(21, RG8I, SINT)
_p(28, RGB8I, SINT)
_p(42, RGBA8I, SINT)
_p(70, R16Unorm, UNORM)
_p(77, RG16Unorm, UNORM)
_p(84, RGB16Unorm, UNORM)
_p(91, RGBA16Unorm, UNORM)
_p(71, R16Snorm, SNORM)
_p(78, RG16Snorm, SNORM)
_p(85, RGB16Snorm, SNORM)
_p(92, RGBA16Snorm, SNORM)
_p(74, R16UI, UINT)
_p(81, RG16UI, UINT)
_p(88, RGB16UI, UINT)
_p(95, RGBA16UI, UINT)
_p(75, R16I, SINT)
_p(82, RG16I, SINT)
_p(89, RGB16I, SINT)
_p(96, RGBA16I, SINT)
_p(98, R32UI, UINT)
_p(101, RG32UI, UINT)
_p(104, RGB32UI, UINT)
_p(107, RGBA32UI, UINT)
_p(99, R32I, SINT)
_p(102, RG32I, SINT)
_p(105, RGB32I, SINT)
_p(108, RGBA32I, SINT)
_p(76, R16F, SFLOAT)
_p(83, RG16F, SFLOAT)
_p(90, RGB16F, SFLOAT)
_p(97, RGBA16F, SFLOAT)
_p(100, R32F, SFLOAT)
_p(103, RG32F, SFLOAT)
_p(106, RGB32F, SFLOAT)
_p(109, RGBA32F, SFLOAT)
_p(124, Depth16Unorm, UNORM)
_p(125, Depth24Unorm, UNORM)
_p(126, Depth32F, SFLOAT)
_p(127, Stencil8UI, UINT)
_p(128, Depth16UnormStencil8UI, UINT)
_p(129, Depth24UnormStencil8UI, UINT)
_p(130, Depth32FStencil8UI, UINT)
#endif
#ifdef _c /* CompressedPixelFormat */
_c(131, Bc1RGBUnorm, UNORM)
_c(132, Bc1RGBSrgb, SRGB)
_c(133, Bc1RGBAUnorm, UNORM)
_c(134, Bc1RGBASrgb, SRGB)
_c(135, Bc2RGBAUnorm, UNORM)
_c(136, Bc2RGBASrgb, SRGB)
_c(137, Bc3RGBAUnorm, UNORM)
_c(138, Bc3RGBASrgb, SRGB)
_c(139, Bc4RUnorm, UNORM)
_c(140, Bc4RSnorm, SNORM)
_c(141, Bc5RGUnorm, UNORM)
_c(142, Bc5RGSnorm, SNORM)
_c(143, Bc6hRGBUfloat, UFLOAT)
_c(144, Bc6hRGBSfloat, SFLOAT)
_c(145, Bc7RGBAUnorm, UNORM)
_c(146, Bc7RGBASrgb, SRGB)
_c(153, EacR11Unorm, UNORM)
_c(154, EacR11Snorm, SNORM)
_c(155, EacRG11Unorm, UNORM)
_c(156, EacRG11Snorm, SNORM)
_c(147, Etc2RGB8Unorm, UNORM)
_c(148, Etc2RGB8Srgb, SRGB)
_c(149, Etc2RGB8A1Unorm, UNORM)
_c(150, Etc2RGB8A1Srgb, SRGB)
_c(151, Etc2RGBA8Unorm, UNORM)
_c(152, Etc2RGBA8Srgb, SRGB)
_c(157, Astc4x4RGBAUnorm, UNORM)
_c(158, Astc4x4RGBASrgb, SRGB)
_c(1000066000, Astc4x4RGBAF, SFLOAT)
_c(159, Astc5x4RGBAUnorm, UNORM)
_c(160, Astc5x4RGBASrgb, SRGB)
_c(1000066001, Astc5x4RGBAF, SFLOAT)
_c(161, Astc5x5RGBAUnorm, UNORM)
_c(162, Astc5x5RGBASrgb, SRGB)
_c(1000066002, Astc5x5RGBAF, SFLOAT)
_c(163, Astc6x5RGBAUnorm, UNORM)
_c(164, Astc6x5RGBASrgb, SRGB)
_c(1000066003, Astc6x5RGBAF, SFLOAT)
_c(165, Astc6x6RGBAUnorm, UNORM)
_c(166, Astc6x6RGBASrgb, SRGB)
_c(1000066004, Astc6x6RGBAF, SFLOAT)
_c(167, Astc8x5RGBAUnorm, UNORM)
_c(168, Astc8x5RGBASrgb, SRGB)
_c(1000066005, Astc8x5RGBAF, SFLOAT)
_c(169, Astc8x6RGBAUnorm, UNORM)
_c(170, Astc8x6RGBASrgb, SRGB)
_c(1000066006, Astc8x6RGBAF, SFLOAT)
_c(171, Astc8x8RGBAUnorm, UNORM)
_c(172, Astc8x8RGBASrgb, SRGB)
_c(1000066007, Astc8x8RGBAF, SFLOAT)
_c(173, Astc10x5RGBAUnorm, UNORM)
_c(174, Astc10x5RGBASrgb, SRGB)
_c(1000066008, Astc10x5RGBAF, SFLOAT)
_c(175, Astc10x6RGBAUnorm, UNORM)
_c(176, Astc10x6RGBASrgb, SRGB)
_c(1000066009, Astc10x6RGBAF, SFLOAT)
_c(177, Astc10x8RGBAUnorm, UNORM)
_c(178, Astc10x8RGBASrgb, SRGB)
_c(1000066010, Astc10x8RGBAF, SFLOAT)
_c(179, Astc10x10RGBAUnorm, UNORM)
_c(180, Astc10x10RGBASrgb, SRGB)
_c(1000066011, Astc10x10RGBAF, SFLOAT)
_c(181, Astc12x10RGBAUnorm, UNORM)
_c(182, Astc12x10RGBASrgb, SRGB)
_c(1000066012, Astc12x10RGBAF, SFLOAT)
_c(183, Astc12x12RGBAUnorm, UNORM)
_c(184, Astc12x12RGBASrgb, SRGB)
_c(1000066013, Astc12x12RGBAF, SFLOAT)
_c(1000054000, PvrtcRGBA2bppUnorm, UNORM)
_c(1000054004, PvrtcRGBA2bppSrgb, SRGB)
_c(1000054001, PvrtcRGBA4bppUnorm, UNORM)
_c(1000054005, PvrtcRGBA4bppSrgb, SRGB)
#endif
